name: travel_share
description: "TravelShare - Chia sẻ chi phí đi lại và du lịch."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.2.1 
  cupertino_icons: ^1.0.6


  # Quản lý trạng thái
  provider: ^6.1.2
  
  # Mạng và API
  dio: ^5.8.0+1
  json_annotation: ^4.8.1
  
  # Lưu trữ cục bộ
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^9.0.0
  
  # UI/UX
  flutter_svg: ^2.0.10
  cached_network_image: ^3.3.1
  intl: ^0.18.1
  flutter_localizations:
    sdk: flutter
  google_fonts: ^6.2.1
  shimmer: ^3.0.0
  
  # Điều hướng
  jwt_decoder: ^2.0.1
  image_picker: ^1.1.2
  video_player: ^2.9.2
  
  # File operations & sharing
  image_gallery_saver: ^2.0.3
  share_plus: ^10.0.0
  permission_handler: ^11.3.1
  path_provider: ^2.1.4
  path: ^1.9.0
  device_info_plus: ^10.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.8
  json_serializable: ^6.7.1
  mockito: ^5.4.4

flutter:
  uses-material-design: true
  
  # Thêm thư mục assets khi cần
  assets:
    - .env
    - assets/images/

